name: build
on:
  push:
    tags:
      - 'v*'
jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 初始化node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: build-dist
        run: npm run build:web
      - name: gen-file
        run: tar -zcvf web.tar.gz dist/web
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body-path: README.md
          files: web.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
